### ISSUE TITLE
Move Kilosort results to a subdirectory for `sessid` 758539

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/bl_pipeline_python#13]
- Based on the logic of the `element-array-ephys` the Kilosort results should be in a subdirectory of the session directory.
- Can we move the Kilosort results to a subdirectory and change the path in `acquisition.AcquisitionSessions`?

**Comment by kabilar** [comment]
Hi @Alvalunasan, would this be possible for `sessid` 758539?  If there are more cases, I will have to think about a smarter way for the `element` to handle this situation.  Thanks.

**Comment by Alvalunasan** [comment]
I think we can enforce to have kilosort results in a subdirectory. I will talk with ephys team about it.

**Comment by Alvalunasan** [comment]
![Uploading Screen Shot 2021-10-21 at 9.10.59 AM.png…]()

**Comment by Alvalunasan** [comment]
<img width="630" alt="Screen Shot 2021-10-21 at 9 10 59 AM" src="https://user-images.githubusercontent.com/56653225/138299712-2321d2ee-1491-40ef-8d92-02d5689c078d.png">

**Comment by kabilar** [comment]
Only instances of session directory containing kilosort results that are not in a subdirectory:

<img width="346" alt="image1" src="https://user-images.githubusercontent.com/871137/138316535-14645133-7293-45cf-aa71-e6d8df943673.png">

Session 751666 possibly does not have an issue because there is also other directory with some kilosort results for that subject and date: `Thomas/T219/T219_2019_12_05/spikesort_2019_12_09_01_01_01_ks2jrc_thomas`

**Comment by Alvalunasan** [comment]
Hi Kabi, Adrian agreed to correct these sessions (by creating a SORT_ID) subfolder. 
Also, the SORT_ID subfolder should be enforced in the future

**Comment by kabilar** [comment]
Great.  Thank you.

**Comment by Alvalunasan** [comment]
Ephys pipeline in brodylab is not used at all so I will close this issue.
