### ISSUE TITLE
Single animal has multiple probes for chronic ephys element

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/bl_pipeline_python#7]
- Probe serial number does not match database entry for a few datasets
- For chronic experiments
    - Have they recorded with different probes for a single subject?
    - Have they used multiple probes simultaneously?

**Comment by Alvalunasan** [comment]
Have they recorded with different probes for a single subject? **Yes**
Have they used multiple probes simultaneously? **Yes**

It would be amazing that pipeline can handle this

**Comment by Alvalunasan** [comment]
Ephys pipeline in brodylab is not used at all so I will close this issue.
