### ISSUE TITLE
Store Kilosort version and parameters

### ISSUE THREAD

**Issue by kabilar** [datajoint-company/bl_pipeline_python#8]
- Need to determine if we want to store the Kilosort version and analysis parameters for each entry.
- If so, we need to determine where these are located.  `rez.mat` within Kilosort results directory
- Load and insert the parameters for each entry in the ingestion script.

**Comment by Alvalunasan** [comment]
They do not store kilosort version but it can be deducted by parameters used if necessary.
For the automatic pipeline, we could create a task to store kilosort version.
_______
Or even,  we could include:
**Algorithm**, 
**Version**,
**HASH** of repository

**Comment by Alvalunasan** [comment]
Not a priority right now.
